-- Migration: groups
-- Description: Friend groups / cohorts
-- Docs: docs/backend_schema.md §3.2

-- TODO: CREATE TABLE public.groups (
--   id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--   name text NOT NULL,
--   owner_id uuid NOT NULL REFERENCES public.profiles(id),
--   invite_code text UNIQUE NOT NULL,
--   created_at timestamptz DEFAULT now()
-- );
