-- Migration: sessions
-- Description: Core focus session entity
-- Docs: docs/backend_schema.md §3.4

-- TODO: CREATE TABLE public.sessions (
--   id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--   user_id uuid NOT NULL REFERENCES public.profiles(id),
--   group_id bigint REFERENCES public.groups(id),
--   spot_id bigint REFERENCES public.spots(id),
--   title text NOT NULL,
--   category text,
--   start_time timestamptz NOT NULL,
--   end_time timestamptz,
--   status text NOT NULL DEFAULT 'active',
--   target_duration_minutes int NOT NULL,
--   duration_minutes int,
--   goal_completed boolean,
--   notes text,
--   summary_ai text,
--   visibility text NOT NULL DEFAULT 'group',
--   created_at timestamptz DEFAULT now()
-- );
