-- Migration: spots
-- Description: Campus study locations
-- Docs: docs/backend_schema.md §3.1

-- TODO: CREATE TABLE public.spots (
--   id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--   name text NOT NULL,
--   description text,
--   area text,
--   lat numeric,
--   lng numeric,
--   tags text[],
--   created_at timestamptz DEFAULT now()
-- );
