-- Migration: rls_policies
-- Description: Enable RLS and create access policies for all tables
-- Docs: docs/backend_schema.md §2–3, docs/implementation_plan.md Phase 1

-- TODO: ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
-- TODO: ALTER TABLE public.spots ENABLE ROW LEVEL SECURITY;
-- TODO: ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;
-- TODO: ALTER TABLE public.group_members ENABLE ROW LEVEL SECURITY;
-- TODO: ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
-- TODO: ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
-- TODO: ALTER TABLE public.deadlines ENABLE ROW LEVEL SECURITY;
-- TODO: CREATE POLICY ... for each table
