-- Migration: deadlines
-- Description: Manual deadlines for study suggestions (optional MVP)
-- Docs: docs/backend_schema.md §3.6

-- TODO: CREATE TABLE public.deadlines (
--   id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--   user_id uuid NOT NULL REFERENCES public.profiles(id),
--   course text,
--   title text,
--   due_at timestamptz,
--   created_at timestamptz DEFAULT now()
-- );
